### ISSUE TITLE
Build CI/CD Pipeline

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/quarkus-monitor#9]
To enable faster and more precise code reviews and automatic package push to maven central, a CI/CD pipeline should be built with Github Actions (or any other open source provider - Circle CI, Jenkins, Travis...).

The pipeline should have at least Pull Requests and Releases triggers.

**Comment by gilliardmacedo** [comment]
In progress. 
PR #10 creates pull request build pipeline. I'm going to create release pipeline.

**Comment by gilliardmacedo** [comment]
Ticket opened to register the new namespace at maven central
https://issues.sonatype.org/browse/OSSRH-62658

**Comment by gilliardmacedo** [comment]
@abilioesteves 

OSSRH commented:

"A staging repository is already configured for the groupId br.com.labbs. Can you have someone with a deployer role comment on this ticket to verify your request?"

Can you help me with this?

**Comment by abilioesteves** [comment]
@gilliardmacedo, I'm looking into this with @KarineValenca. Thank you!

**Comment by gilliardmacedo** [comment]
@abilioesteves The ticket was resolved and now I have the access, but with many questions:

Github actions needs Sonatype username and password to deploy artifacts. This can be done with secrets:
https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository

We need a Sonatype labbs/impersonal user?

After decide what credentials we will use, an organization admin needs to set this credentials in a secret.

Note this can be an one-time setup for all Java artifacts.
